### ISSUE TITLE
Create models for events, participants, and time slots

### ISSUE THREAD

**Issue by dev-magic** [dev-magic/letsmeetup#1]
We need to come up with a data model to represent events, participants/users, and time slots.

**Comment by appleJax** [comment]
Here's a  sketch of how we could structure our models. This is the first time I've tried to construct a data model in rails, so please correct me if I'm misunderstanding how this stuff works.

Regarding the "preference" field on the Preference model, I gave it the "integer" type. I was thinking we could represent preferences like so:

red = 0
white = 1
yellow = 2
green = 3
blue = 4

Then we could add up the numbers for all the participants, and the higher-scoring slots would get priority. We could filter the view of available timeslots to remove any slots that contain a zero.


<table>
  <thead>
    <tr>
      <th colspan=2 style="font-size: 1.7em">Event</th>
    </tr>
    <tr>
      <th colspan=2>has_many :users</th>
    </tr>
    <tr>
      <th colspan=2>has_many :timeslots</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>id</td>
      <td>integer</td>
    </tr>
    <tr>
      <td>name</td>
      <td>string</td>
    </tr>
    <tr>
      <td>location</td>
      <td>string</td>
    </tr>
    <tr>
      <td>time</td>
      <td>datetime</td>
    </tr>
  </tbody>
</table>

<br>
<br>

<table>
  <thead>
    <tr>
      <th colspan=2 style="font-size: 1.7em">User</th>
    </tr>
    <tr>
      <th colspan=2>has_many :events</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>id</td>
      <td>integer</td>
    </tr>
    <tr>
      <td>name</td>
      <td>string</td>
    </tr>
  </tbody>
</table>

<br>
<br>

<table>
  <thead>
    <tr>
      <th colspan=2 style="font-size: 1.7em">events_users</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>event_id</td>
      <td>integer</td>
    </tr>
    <tr>
      <td>user_id</td>
      <td>integer</td>
    </tr>
  </tbody>
</table>

<br>
<br>

<table>
  <thead>
    <tr>
      <th colspan=2 style="font-size: 1.7em">Timeslot</th>
    </tr>
    <tr>
      <th colspan=2>belongs_to :event</th>
    </tr>
    <tr>
      <th colspan=2>has_many :preferences, :through => :event</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>event_id</td>
      <td>integer</td>
    </tr>
    <tr>
      <td>start_time</td>
      <td>datetime</td>
    </tr>
  </tbody>
</table>

<br>
<br>

<table>
  <thead>
    <tr>
      <th colspan=2 style="font-size: 1.7em">Preference</th>
    </tr>
    <tr>
      <th colspan=2>belongs_to :timeslot</th>
    </tr>
    <tr>
      <th colspan=2>belongs_to :user</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timeslot_id</td>
      <td>integer</td>
    </tr>
    <tr>
      <td>user_id</td>
      <td>integer</td>
    </tr>
     <tr>
      <td>preference</td>
      <td>integer</td>
    </tr>
  </tbody>
</table>


Let me know if you have any questions about this proposal, and feel free to offer corrections and/or alternatives!

**Comment by gabrielbonner** [comment]
@appleJax Looks right to me, although you might want to add an `email` and `hashed_password` fields to the User table.  Also, do we want to include an `end_time` or `approx_duration` (defaulted to 1 hour, perhaps) to `Timeslot`s?

**Comment by appleJax** [comment]
@gabrielbonner good call. I added an email field to User, and a duration field to Event. That way each Timeslot for an event is defined by its start_time, and the end_time for each Timeslot is based off the duration of the Event.
