### ISSUE TITLE
Create Nav and Footer for application layout view

### ISSUE THREAD

**Issue by appleJax** [dev-magic/letsmeetup#11]
We need an application-wide Nav bar and Footer. Could be implemented as react components, but doesn't have to be.

**Comment by gabrielbonner** [comment]
...which means we need to decide on a group name and a logo sooner rather than later!  :D

**Comment by appleJax** [comment]
I personally like Dev Magic, open to other options though. It just reminds me of Arthur C. Clarke's quote "Any sufficiently advanced technology is indistinguishable from magic."  🔥
