### ISSUE TITLE
Implement "Add new event" functionality

### ISSUE THREAD

**Issue by appleJax** [dev-magic/letsmeetup#16]
We need to put a button on the home page to create a new event.

**Comment by gabrielbonner** [comment]
I'm going to get started on this now, but will be out this evening and tomorrow evening.  If someone has time and wants to bust it out before Monday night (when I'll most likely be finished), go for it!  :)

**Comment by kylestengline** [comment]
Are users logging in before they can add a new event? Or is it just open? I'm working on the testing for this, but wasn't sure if users should have log in before they can create a new event.

**Comment by appleJax** [comment]
@kylestengline eventually, I think users should have to log in before making changes to anything. We still need to set up authentication though, so we can circle back around and add authorization once we have the mechanisms in place.
