### ISSUE TITLE
WIP: Hook "/event/:id" component up to the models

### ISSUE THREAD

**Issue by appleJax** [dev-magic/letsmeetup#21]
We need to wire up the view for an individual event to our models.

**Comment by appleJax** [comment]
@jeremyjung do you wanna take a crack at this one?

**Comment by jeremyjung** [comment]
So this means creating an EventsController and creating a /events/:id route in rails that when you go there, shows the event at that id?

**Comment by appleJax** [comment]
@jeremyjung yep. We already have the Event react component, just need to make it display information from the model instead of the hardwired info that is currently there.
