### ISSUE TITLE
Implement "User sign up" functionality

### ISSUE THREAD

**Issue by appleJax** [dev-magic/letsmeetup#26]
We need Users!!!

**Comment by appleJax** [comment]
@kylestengline do you wanna tackle this one?

**Comment by kylestengline** [comment]
I can do this one. Did we want clearance or something that can handle OAuth with FB, twitter, etc? As far as I know, clearance doesn't have an OAuth option, but I could be wrong.

**Comment by appleJax** [comment]
It would be nice to use OAuth, so we don't have to remember another password.

**Comment by kylestengline** [comment]
I agree. That may only leave devise? I did a quick search and CanCan seems messy and I don't think can handle OAuth. Do you know of another gem that handles OAuth?

**Comment by appleJax** [comment]
OmniAuth, it's really lightweight as well. Devise is fine though. Probably overkill for this project, but I've never used it, so I'd be interested to learn about it.

**Comment by kylestengline** [comment]
Oh, I see. Should we only have OAuth? It looks like there is no email, password login combo, only FB, google, etc. Should we go that route?

**Comment by appleJax** [comment]
Ooohh. I think email/password authentication is just another `strategy`. https://github.com/intridea/omniauth-identity

**Comment by kylestengline** [comment]
Nice! I see it now. They event have a railscasts on how to use it for the basic auth. (email/password) combo. I'll read more on this and get started.

**Comment by jeremyjung** [comment]
I think if we are going to use oauth and username/password we might as well use devise.

**Comment by kylestengline** [comment]
I'm good with that. Also, thinking long term, if we eventually want to send mailers, devise has configurations for that too. Those can be customized as well.

**Comment by gabrielbonner** [comment]
🎉
