### ISSUE TITLE
Implement "Click-to-Change-Preference" on /events/:id component

### ISSUE THREAD

**Issue by appleJax** [dev-magic/letsmeetup#27]
In the /events/:id component, we need to add the ability to click on a table cell to change our "Preference" for that Timeslot in the database.

**Comment by gabrielbonner** [comment]
I was thinking about if we should be able to see other users' preferences when we are choosing our own, or if we should do it in a 'vacuum'.  The first route seems fine for our group, but just thought I'd mention it in case we wanted to start making decisions based on this app having extensibility to other groups/projects/purposes in the future.

**Comment by appleJax** [comment]
I kinda like the idea of only seeing your own choices. We could have a default /events/:id view that just has the event information, list of attendees (users), etc, and we'd have a "Fill In Your Availability" button or something. We'd need to add the concept of an event "owner" to allow someone to have access to the master list of everyone's availability in cases where a single "best" timeslot can't be chosen automatically.

**Comment by gabrielbonner** [comment]
It could be a toggle when creating an Event to make it a "blind" event, where users can't see others' preferences.
