### ISSUE TITLE
Send out a confirmation email when a new user signs up

### ISSUE THREAD

**Issue by kylestengline** [dev-magic/letsmeetup#44]
Adding test specs for this as well.

**Comment by kylestengline** [comment]
Any ideas for what the confirmation email should say? 
I'm thinking:

> Thanks for signing up to <insert cool name here>. Please click the link below to confirm your email. Thanks!

**Comment by appleJax** [comment]
That sounds good... and we should include a random picture of Chuck Norris.

**Comment by kylestengline** [comment]
Consider it done!
