### ISSUE TITLE
Add RSpec tests for Events/Users/Timeslots models to Jeremy's branch

### ISSUE THREAD

**Issue by gabrielbonner** [dev-magic/letsmeetup#7]

**Comment by kylestengline** [comment]
Committed passing model specs with associations to my branch. Will refactor 8/30, tomorrow night.

**Comment by kylestengline** [comment]
Fixed conflicts with rebasing within my master branch. Model specs pass with updated `location` table and `duration_minutes`.

**Comment by appleJax** [comment]
@kylestengline so it's working now?

**Comment by kylestengline** [comment]
@appleJax yep, it's working now. I haven't made a pull-request or anything though.
