### ISSUE TITLE
Add testing for "Add new event" functionality

### ISSUE THREAD

**Issue by kylestengline** [dev-magic/letsmeetup#8]

**Comment by appleJax** [comment]
@kylestengline are you working on this one? If not, issue #22 is a good one to look into.

**Comment by kylestengline** [comment]
@appleJax I can work on this one. 
How do we see this working? Is the user filling out a short form, picking the time slots, adding an event name, etc? I see @gabrielbonner is working on the implementation in issue [#16](https://github.com/dev-magic/letsmeetup/issues/16).

**Comment by appleJax** [comment]
@kylestengline yeah, there will probably be a "Add Event" button on the home page that will take you to a form for creating a new event. I'm just now realizing the "new event" form will have to have a sub-form for either picking an existing location or creating a new location.

**Comment by kylestengline** [comment]
@appleJax just thinking about this...should we have a google maps API integrated with creating/picking locations? I'm thinking you could enter an address or enter the name of a place and it will be able to find that location within a map. Thoughts?

**Comment by appleJax** [comment]
@kylestengline  Yeah, that would be sweet.
